# Generated by Django 4.0.4 on 2022-06-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=70, null=True)),
                ('CompanyAddress', models.CharField(max_length=70)),
                ('Logo', models.ImageField(upload_to='uploads/')),
                ('phoneno', models.BigIntegerField(null=True)),
            ],
        ),
    ]
